#!/bin/bash


gnome-terminal -e "python -m SimpleHTTPServer"

#gnome-terminal -e "python ../src/client.py"
#gnome-terminal -e "python ../src/client1.py"
#gnome-terminal -e "python ../src/client2.py"

gnome-terminal -e "python host.py"

